name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sed -i '/psycopg2/d' requirements.txt
          pip install -r requirements.txt

      # Step 4: Run the tests with pytest
      - name: Run tests
        run: |
          pytest > pytest_output.txt
          cat pytest_output.txt

      # Step 5: Post pytest results as a comment on the pull request
      - name: Comment pytest results on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.9.0
        with:
          path: pytest_output.txt